import type { Metadata } from 'next'
import { Analytics } from '@vercel/analytics/react'
import { GeistSans } from 'geist/font/sans'

import './globals.css'

import { Sidebar } from '@/components/sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={GeistSans.className}>
        <main vaul-drawer-wrapper="" className="min-h-screen bg-white">
          <div className="lg:flex">
            <div className="flex flex-1">{children}</div>
            <Sidebar>hello</Sidebar>
          </div>
        </main>
        <Analytics />
      </body>
    </html>
  )
}

export default RootLayout
